
DROP TABLE IF EXISTS classes CASCADE;
CREATE TABLE classes (
  id SERIAL PRIMARY KEY NOT NULL,
  employee_id INTEGER REFERENCES employees(id) ON DELETE CASCADE,
  duration INTEGER NOT NULL,
  date DATE NOT NULL,
  isFull BOOLEAN NOT NULL
);
